config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, path: 'users'
  
  resources :users do
    resources :domains, only: [:index, :create, :show, :new] do
      resources :ranks, only:[:create]
    end
  end

  root to: 'domains#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user
  has_many :ranks, dependent: :destroy
  validates_uniqueness_of :name, scope: :user_id, message: "You alredy entered that domain"
  validates_presence_of :name
  validate :user_quota, on: :create
  
  def user_quota
    errors.add(:base, 'OOps!!! You have Exceeded maximum domain limit/user (3)')  if self.user.domains(:reload).count >= 3
  end
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  belongs_to :domain
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :domains
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :zxcvbnable
  
  # Override Devise method to send mails in background
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
    
    def today
      Date.today.strftime("%Y-%m-%d")
    end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  include Alexa
  
  def index
    @domain = current_user.domains.build
  end
  
  def new
    @domain = Domain.new
  end
  
  def create
    @url = params[:domain][:name]
    @domain_rank =  get_alexa_rank
    @domain = current_user.domains.build(domain_params)
    @rank = @domain.ranks.build(rank: @domain_rank, date: today)
    respond_to do |format|
      if @domain_rank != nil && @domain_rank != "-"
        if @domain.save
          @rank.save
          format.html { redirect_to user_domain_path(user_id: @domain.user_id, id: @domain.id), notice: "Domain saved successfully" }
          format.json { render :show, status: :created, location: @domain }
        else
          format.html { render :index }
          format.json { render json: @domain.errors, status: :unprocessable_entity }
        end        
      else
        format.html { redirect_to root_path, notice: "No rank found for #{@url}" }
        format.json { render json: {'status': 'unprocessable_entity'} }
      end
    end
  end
  
  def show
    @domain_data = User.includes(domains: [:ranks]).find(current_user.id)
  end
  
  private
    
    def domain_params
      params.require(:domain).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
  
  def quota_reached?
    current_user.domains.count >= 3
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain, url: user_domains_path(@domain.user_id),  html: { html: {id: "new_domain", class: "new_domain"}}) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>
      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter / Paste a URL" %>
  </div>
  <div>&nbsp</div>
  <div class="actions">
    <%= f.submit 'Get Rank', :class => "btn btn-info"%>
  </div>
<% end %>

app/views/domains/index.html.erb
<% content_for :top_content do %>
  <div class="center jumbotron">
    <h1>Welcome to AlexaRank!</h1>
    <div class="container">
        <% if !quota_reached? %>
          <div>&nbsp</div>
          <%= render 'domains/form' %>
        <% else %>
          <h4>Reached Max Domains/User(3)</h4>
          <%= link_to "See your Domains", user_domain_path(user_id: current_user.id, id: current_user.domains.first.id), class: "btn btn-primary" %>
        <% end %>
        <div class="result"></div>
    </div>
  </div>
<% end %>

app/views/domains/show.html.erb
<div class="container">

  <table class="table table-inverse">
    <thead>
      <tr>
        <th>Domain</th>
        <th>Rank</th>
        <th>Last Updated</th>
      </tr>
    </thead>
    <tbody>
      <% @domain_data.domains.each do |domain| %>
        <tr>
          <td scope="row"><b><i><%= domain.name %></i></b></td>
          <td><b><%= domain.ranks.last.rank %></b></td>
          <td><b><%= domain.ranks.last.date %></b></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id="rank_graph"></div>
  <div class="row">
    
      <% if !quota_reached? %>
        <div class="col-xs-4 col-sm-3 col-lg-2">
          <%= link_to "New Domain", root_path, class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="col-xs-12 col-sm-12 col-lg-12">
          <h4>You have reached the limit of 3 domains/user</h4>
        </div>
      <% end %>
    
  </div>
</div>



<script>
  $(function(){
    var grph_var = Highcharts.chart('rank_graph', {
        title: {
            text: 'Alexa Ranks Comparison',
            x: -20 //center
        },
        subtitle: {
            text: 'Source: Alexa.com',
            x: -20
        },
        xAxis: {
            type: "category",
            title: {
            text: 'Dates'
          }
        },
        yAxis: {
            title: {
                text: 'Alexa Rank',
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }],
            reversed: true,
        },
        tooltip: {
            valuePrefix: 'Rank:',
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [
          <% @domain_data.domains.each do |domain| %>
            { 
              name: "<%= domain.name.sub(/^https?\:\/\//, '') %>",
              data: <%= raw (domain.ranks.limit(10)).map { |rank| [rank.date.strftime('%Y-%m-%d'), rank.rank.gsub(/,/,'').to_i]}.inspect %>
            },
          <% end %>
        ]
    });    
  });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Alexa rank tracking App
    by Tony Vincent
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlexaRank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'AlexaRank', root_path, class: 'navbar-brand', id: 'logo' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  <div class="container">
    <%= yield :top_content %>
    <h1><%= yield :header %></h1>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>